### PR TITLE
Fix battery status

### PR DESCRIPTION
**Pull request by Divyansh2512**
Fixes the battery status as `$battery` doesn't seem to work.

### CODE REVIEW

**Comment by ritiek** [comment]
A better way could be to modify the target in [battery.sh](https://github.com/ritiek/dotfiles/blob/185fcda116ade395151d43975456ba56f2ef514b/battery.sh) to `BAT0`. I think I kept it to `BAT1` since maybe that's what it pointed to on my old laptop. But yes, I think `BAT0` should be more consistent than `BAT1` on modern laptops.

`battery` is then added to PATH from [here](https://github.com/ritiek/dotfiles/blob/185fcda116ade395151d43975456ba56f2ef514b/setup.sh#L344-L349) and should then be automatically picked up by .zshrc. So this change in battery.sh should be all that is needed to fix the problem.

**Comment by Divyansh2512** [comment]
I've made the changes kindly review and let me know in case of any discrepancy!
And can I ask why you have created a separate file for battery status? I mean you could've created a variable battery and stored the path inside it just like cpuTemp and gpuTemp!

**Comment by ritiek** [comment]
> And can I ask why you have created a separate file for battery status? I mean you could've created a variable battery and stored the path inside it just like cpuTemp and gpuTemp!

I think it's there due to historical reasons. In the past, when I didn't use powerline for tmux (and therefore didn't have access to powerline's built-in methods to access battery levels), I'd call this `battery` command as a part of refreshing my tmux's status-line every few seconds (https://github.com/ritiek/dotfiles/commit/bb7e1412e045943f36352329a9277447055da97d). So this `battery` command helped both in `.zshrc` and `.tmux.conf` back then.

This `battery` command isn't used anywhere outside of `.zshrc` as of today (since I now use powerline for tmux), so I think we could work this out similar to how `cpuTemp` and `gpuTemp` are currently implemented in `.zshrc`.

**Comment by Divyansh2512** [comment]
I believe we can consider removing `battery.sh` and `pretty-uptime.sh` files as they are not being used now!

**Comment by ritiek** [comment]
Yep, sounds good to me!

**Comment by Divyansh2512** [comment]
Let me know in case if anything is incorrect from my end!

**Pull request merged**
